events {}

http {

  # Prowlarr
  server {
    listen 80;
    server_name prowlarr.local;
    location / {
      proxy_pass http://gluetun:9696;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # Jackett
  server {
    listen 80;
    server_name jackett.local;
    location / {
      proxy_pass http://gluetun:9117;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # Sonarr
  server {
    listen 80;
    server_name sonarr.local;
    location / {
      proxy_pass http://gluetun:8989;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # Radarr
  server {
    listen 80;
    server_name radarr.local;
    location / {
      proxy_pass http://gluetun:7878;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # Bazarr
  server {
    listen 80;
    server_name bazarr.local;
    location / {
      proxy_pass http://gluetun:6767;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # Trailarr
  server {
    listen 80;
    server_name trailarr.local;
    location / {
      proxy_pass http://gluetun:7889;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # qBittorrent
  server {
    listen 80;
    server_name qbittorrent.local;
    location / {
      proxy_pass http://gluetun:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # SABnzbd
  server {
    listen 80;
    server_name sabnzbd.local;
    location / {
      proxy_pass http://gluetun:8085;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  # NZBGet
  server {
    listen 80;
    server_name nzbget.local;
    location / {
      proxy_pass http://gluetun:6789;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

}
